root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

title: RawJade Whitepaper v0.9H
description: From Polycrisis to Polytunity - Multilingual Edition

plugins:
  - search
  - fontsettings
  - theme-default
  - advanced-emoji

# 다국어 지원 설정
variables:
  languages:
    ko: "한국어"
    en: "English"
