root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

title: RawJade Whitepaper v0.9H
description: From Polycrisis to Polytunity

plugins:
  - search
  - fontsettings
  - theme-default

# 강제 업데이트를 위한 타임스탬프
updated: 2025-08-12 16:13:15
