root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

title: RawJade 백서 v0.9H
description: 다중위기에서 다중기회로 - 참여 경제의 혁명적 비전

# 한국어를 메인 언어로 설정
defaultLanguage: ko

plugins:
  - search
  - fontsettings  
  - theme-default
